### Get invite info
GET {{host}}/api/data/inviteInfo/6098fe17-d26e-457d-b59a-878a94af8978
Content-Type: application/json

> {%
    client.test('get invite info', function() {
        client.assert(response.status === 200, "Remove guest OK");
    });
%}


### Post invite info survey
POST {{host}}/api/data/inviteInfo/surveyResponse
Content-Type: application/json

{
  "inviteId": "bad7e35f-d1d8-4b97-9342-1f2ba78b8b24",
  "presentGuests": [
    "6648ca50a958ee13ce20f85d"
  ],
  "startPlace": "church",
  "isPrivateTransport": false,
  "presentOnSecondDay": [
    "6648ca50a958ee13ce20f85d"
  ],
  "needSleepPlace": false,
  "likeDrinks": [
    "vodca",
    "beer"
  ]
}


> {%
  client.test('post invite info survey', function() {
    client.assert(response.status === 200, "Post invite info survey OK");
  });
%}

### Post invite info survey - empty presentGuests
POST {{host}}/api/data/inviteInfo/surveyResponse
Content-Type: application/json

{
  "inviteId": "bad7e35f-d1d8-4b97-9342-1f2ba78b8b24",
  "presentGuests": []
}


> {%
  client.test('post invite info survey', function() {
    client.assert(response.status === 200, "Post invite info survey OK");
  });
%}


