### Login admin
POST {{host}}/api/data/auth/login/guest
Content-Type: application/json

{
  "inviteId": "bad7e35f-d1d8-4b97-9342-1f2ba78b8b24"
}

> {%
    client.test('Login admin', function() {
        client.assert(response.status === 200, "Login user failed");
        client.global.set('accessToken', response.body.data.accessToken)
    });
%}

### Get invite info
GET {{host}}/api/data/inviteInfo
Content-Type: application/json
Authorization: Bearer {{accessToken}}

> {%
    client.test('get invite groups', function() {
        client.assert(response.status === 200, "Remove guest OK");
    });
%}




