### Login admin
POST {{host}}/api/data/auth/login/admin
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

> {%
    client.test('Login admin', function() {
        client.assert(response.status === 200, "Login user failed");
        client.global.set('accessToken', response.body.data.accessToken)
    });
%}

### Create invite group
POST {{host}}/api/data/inviteGroups
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "groupName": "Яхимчики 3",
  "guests": [],
  "invitation": {
    "checkSlip": false,
    "checkTransport": true
  }
}

> {%
  client.test('Create invite group', function() {
    client.assert(response.status === 200, "Create invite group OK");
    client.global.set("inviteGroupsId", response.body.data.id)
  });
%}

### Edit invite group
PUT {{host}}/api/data/inviteGroups
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "6648ba0eb86bb5e8934b357b",
  "groupName": "tests",
  "updateGuests": {
    "663ff8a2a947f5482f8b1c02": true
  },
  "invitation": {
    "checkSlip": true,
    "checkTransport": false
  }
}

> {%
    client.test('Create invite group', function() {
        client.assert(response.status === 200, "Create guest OK");
    });
%}

### Remove invite groups
DELETE {{host}}/api/data/inviteGroups/6648bc84f853da853ebc1b76
Content-Type: application/json
Authorization: Bearer {{accessToken}}

> {%
    client.test('Remove invite group', function() {
        client.assert(response.status === 200, "Remove invite group OK");
    });
%}

### Get invite groups
GET {{host}}/api/data/inviteGroups
Content-Type: application/json
Authorization: Bearer {{accessToken}}

> {%
    client.test('get invite groups', function() {
        client.assert(response.status === 200, "Remove guest OK");
    });
%}


### Get invite group by id
GET {{host}}/api/data/inviteGroups/6648b0b40892093293718ba5
Content-Type: application/json
Authorization: Bearer {{accessToken}}

> {%
  client.test('get invite groups', function() {
    client.assert(response.status === 200, "Remove guest OK");
  });
%}



